; Example INI file showing how to pre-configure channel sets
; Name = Default name shown in the first (read-only) edit box
; VirtualChannel = The virtual channel number (read-only) used for mapping

[Set1]
Name=Local News
VirtualChannel=2

[Set2]
Name=Sports
VirtualChannel=3

[Set3]
Name=Movies
VirtualChannel=4

[Set4]
Name=Kids
VirtualChannel=5

[Set5]
Name=Discovery
VirtualChannel=6

[Set6]
Name=History
VirtualChannel=7

[Set7]
Name=Music
VirtualChannel=8

[Set8]
Name=Weather
VirtualChannel=9

[Set9]
Name=Shopping
VirtualChannel=10

[Set10]
Name=Religious
VirtualChannel=11

[Set11]
Name=
VirtualChannel=12

[Set12]
Name=
VirtualChannel=13

[Set13]
Name=
VirtualChannel=14

[Set14]
Name=
VirtualChannel=15

[Set15]
Name=
VirtualChannel=16

[Set16]
Name=
VirtualChannel=17

[Set17]
Name=
VirtualChannel=18

[Set18]
Name=
VirtualChannel=19

[Set19]
Name=
VirtualChannel=20

[Set20]
Name=
VirtualChannel=21

[Set21]
Name=
VirtualChannel=22

[Set22]
Name=
VirtualChannel=23

[Set23]
Name=
VirtualChannel=24

[Set24]
Name=
VirtualChannel=25

[Set25]
Name=
VirtualChannel=26

[Set26]
Name=
VirtualChannel=27

[Set27]
Name=
VirtualChannel=28

[Set28]
Name=
VirtualChannel=29

[Set29]
Name=
VirtualChannel=30

[Set30]
Name=
VirtualChannel=31

[Set31]
Name=
VirtualChannel=32

[Set32]
Name=
VirtualChannel=33

[Set33]
Name=
VirtualChannel=34

[Set34]
Name=
VirtualChannel=35

[Set35]
Name=
VirtualChannel=36

[Set36]
Name=
VirtualChannel=37

[Set37]
Name=
VirtualChannel=38

[Set38]
Name=
VirtualChannel=39

[Set39]
Name=
VirtualChannel=40

[Set40]
Name=
VirtualChannel=41

[Set41]
Name=
VirtualChannel=42

[Set42]
Name=
VirtualChannel=43

[Set43]
Name=
VirtualChannel=44

[Set44]
Name=
VirtualChannel=45

[Set45]
Name=
VirtualChannel=46

[Set46]
Name=
VirtualChannel=47

[Set47]
Name=
VirtualChannel=48

[Set48]
Name=
VirtualChannel=49

[Set49]
Name=
VirtualChannel=50

[Set50]
Name=
VirtualChannel=51

[Set51]
Name=
VirtualChannel=52

[Set52]
Name=
VirtualChannel=53

[Set53]
Name=
VirtualChannel=54

[Set54]
Name=
VirtualChannel=55

[Set55]
Name=
VirtualChannel=56

[Set56]
Name=
VirtualChannel=57

[Set57]
Name=
VirtualChannel=58

[Set58]
Name=
VirtualChannel=59

[Set59]
Name=
VirtualChannel=60

[Set60]
Name=
VirtualChannel=61
